name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.1

      - name: Install dependencies
        run: |
          cd e04
          go mod download

      - name: Build and test Go application
        run: |
          cd e04
          go build -v ./...
          go test -v ./...

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          scan-type: 'fs'

  build-and-push:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./e04
          push: false
          tags: fweingartshofer/my-first-image:${{ github.sha }}

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: fweingartshofer/my-first-image:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          scan-type: 'image'

      - name: Build and tag Docker image
        id: docker_push
        uses: docker/build-push-action@v2
        with:
          context: ./e04
          push: true
          tags: fweingartshofer/my-first-image:${{ github.sha }}
